const SETTINGS = {
  BACKGROUND: "black",
  PARTICLE_SIZE: 4,
  LINE_COLOR: "cyan",
  LINE_LENGTH: 20000,
  FPS: 120,
  CAMERA_SPEED: 1,
  STANDARD_PARTICLE_RADIUS: 1,
  GRAVITATIONAL_CONSTANT: 6.6743e-11,
  DISTANCE_SCALE: 0.2e6
};

export default SETTINGS;